spring.application.name=aeropuerto
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}
# Configuración de Hibernate y JPA
# Define cómo Hibernate gestiona la creación y actualización del esquema de la base de datos
# "none" no actualiza la base de datos de forma automatica y se deja la gestión manual en schema.sql y data.sql
spring.jpa.hibernate.ddl-auto=none
# Muestra las consultas SQL generadas en la consola
spring.jpa.show-sql=true
# Formatea las consultas SQL para que sean más legibles en la consola
spring.jpa.properties.hibernate.format_sql=true
# Dialecto específico de Hibernate para MariaDB (es compatible con MySQL)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# Inicialización de la base de datos
# Esta propiedad asegura que Spring Boot ejecuta los archivos la estructura (schema.sql) y de carga de datos (data.sql) al inicio
spring.sql.init.mode=always
# Define la codificacion de los archivos de propiedades de mensajes.
spring.messages.encoding=UTF-8
# Configuración de los logs del datasource
# Muestra detalles adicionales sobre la conexión a la base de datos
logging.level.org.springframework.jdbc.datasource.DataSourceTransactionManager=DEBUG
# Número máximo de conexiones que puede abrir el pool de conexiones
spring.datasource.hikari.maximum-pool-size=10
