INSERT INTO director (id, nombre, apellidos) VALUES
(1,'Juan','Pérez'),
(2,'María','López'),
(3,'Carlos','García'),
(4,'Ana','Martín'),
(5,'Luis','Rodríguez'),
(6,'Elena','Sánchez'),
(7,'Miguel','Gómez'),
(8,'Sara','Díaz'),
(9,'Javier','Fernández'),
(10,'Laura','Ruiz'),
(11,'Diego','Torres'),
(12,'Carmen','Castro'),
(13,'Pablo','Vargas'),
(14,'Lucía','Ortega'),
(15,'Andrés','Navarro'),
(16,'Sofía','Moreno'),
(17,'Alberto','Domínguez'),
(18,'Natalia','Hernández'),
(19,'Raúl','Iglesias'),
(20,'Patricia','Núñez');

INSERT INTO aeropuerto (id_director, nombre, ciudad, pais, codIata) VALUES
(1,'Aeropuerto Adolfo Suárez Madrid-Barajas','Madrid','España','MAD'),
(2,'Aeropuerto Josep Tarradellas Barcelona-El Prat','Barcelona','España','BCN'),
(3,'Aeropuerto de Sevilla','Sevilla','España','SVQ'),
(4,'Aeropuerto de Valencia','Valencia','España','VLC'),
(5,'Aeropuerto de Bilbao','Bilbao','España','BIO'),
(6,'Aeropuerto de Palma de Mallorca','Palma','España','PMI'),
(7,'Aeropuerto de Málaga-Costa del Sol','Málaga','España','AGP'),
(8,'Aeropuerto de Gran Canaria','Las Palmas','España','LPA'),
(9,'Aeropuerto de Tenerife Sur','Tenerife','España','TFS'),
(10,'Aeropuerto de Tenerife Norte','Santa Cruz de Tenerife','España','TFN'),
(11,'Aeropuerto de Alicante-Elche Miguel Hernández','Alicante','España','ALC'),
(12,'Aeropuerto de Santiago de Compostela','Santiago de Compostela','España','SCQ'),
(13,'Aeropuerto de Asturias','Oviedo','España','OVD'),
(14,'Aeropuerto de Zaragoza','Zaragoza','España','ZAZ'),
(15,'Aeropuerto Federico García Lorca Granada-Jaén','Granada','España','GRX'),
(16,'Aeropuerto de Vigo','Vigo','España','VGO'),
(17,'Aeropuerto de Jerez','Jerez de la Frontera','España','XRY'),
(18,'Aeropuerto de Ibiza','Ibiza','España','IBZ'),
(19,'Aeropuerto de Menorca','Mahón','España','MAH'),
(20,'Aeropuerto de San Sebastián','San Sebastián','España','EAS');