INSERT INTO director (id, nombre, apellidos)
VALUES (1, 'Juan', 'Pérez'),
       (2, 'María', 'López'),
       (3, 'Carlos', 'García'),
       (4, 'Ana', 'Martín'),
       (5, 'Luis', 'Rodríguez'),
       (6, 'Elena', 'Sánchez'),
       (7, 'Miguel', 'Gómez'),
       (8, 'Sara', 'Díaz'),
       (9, 'Javier', 'Fernández'),
       (10, 'Laura', 'Ruiz'),
       (11, 'Diego', 'Torres'),
       (12, 'Carmen', 'Castro'),
       (13, 'Pablo', 'Vargas'),
       (14, 'Lucía', 'Ortega'),
       (15, 'Andrés', 'Navarro'),
       (16, 'Sofía', 'Moreno'),
       (17, 'Alberto', 'Domínguez'),
       (18, 'Natalia', 'Hernández'),
       (19, 'Raúl', 'Iglesias'),
       (20, 'Patricia', 'Núñez');

INSERT INTO aeropuerto (id_director, nombre, ciudad, pais, codIata)
VALUES (1, 'Aeropuerto Adolfo Suárez Madrid-Barajas', 'Madrid', 'España', 'MAD'),
       (2, 'Aeropuerto Josep Tarradellas Barcelona-El Prat', 'Barcelona', 'España', 'BCN'),
       (3, 'Aeropuerto de Sevilla', 'Sevilla', 'España', 'SVQ'),
       (4, 'Aeropuerto de Valencia', 'Valencia', 'España', 'VLC'),
       (5, 'Aeropuerto de Bilbao', 'Bilbao', 'España', 'BIO'),
       (6, 'Aeropuerto de Palma de Mallorca', 'Palma', 'España', 'PMI'),
       (7, 'Aeropuerto de Málaga-Costa del Sol', 'Málaga', 'España', 'AGP'),
       (8, 'Aeropuerto de Gran Canaria', 'Las Palmas', 'España', 'LPA'),
       (9, 'Aeropuerto de Tenerife Sur', 'Tenerife', 'España', 'TFS'),
       (10, 'Aeropuerto de Tenerife Norte', 'Santa Cruz de Tenerife', 'España', 'TFN'),
       (11, 'Aeropuerto de Alicante-Elche Miguel Hernández', 'Alicante', 'España', 'ALC'),
       (12, 'Aeropuerto de Santiago de Compostela', 'Santiago de Compostela', 'España', 'SCQ'),
       (13, 'Aeropuerto de Asturias', 'Oviedo', 'España', 'OVD'),
       (14, 'Aeropuerto de Zaragoza', 'Zaragoza', 'España', 'ZAZ'),
       (15, 'Aeropuerto Federico García Lorca Granada-Jaén', 'Granada', 'España', 'GRX'),
       (16, 'Aeropuerto de Vigo', 'Vigo', 'España', 'VGO'),
       (17, 'Aeropuerto de Jerez', 'Jerez de la Frontera', 'España', 'XRY'),
       (18, 'Aeropuerto de Ibiza', 'Ibiza', 'España', 'IBZ'),
       (19, 'Aeropuerto de Menorca', 'Mahón', 'España', 'MAH'),
       (20, 'Aeropuerto de San Sebastián', 'San Sebastián', 'España', 'EAS');


INSERT INTO avion (id_aeropuerto, modelo, fabricante, capacidad, estado)
VALUES (1, 'A320', 'Airbus', 180, 'Operativo'),
       (2, 'B737-800', 'Boeing', 189, 'Operativo'),
       (3, 'A319', 'Airbus', 144, 'Mantenimiento'),
       (4, 'B777-300ER', 'Boeing', 396, 'Operativo'),
       (5, 'A330-200', 'Airbus', 277, 'Inactivo'),
       (6, 'E190', 'Embraer', 100, 'Operativo'),
       (7, 'A321neo', 'Airbus', 220, 'Operativo'),
       (8, 'B787-9', 'Boeing', 290, 'Operativo'),
       (9, 'CRJ900', 'Bombardier', 90, 'Operativo'),
       (10, 'A350-900', 'Airbus', 325, 'Operativo'),
       (11, 'B767-300', 'Boeing', 261, 'Mantenimiento'),
       (12, 'ATR 72-600', 'ATR', 72, 'Operativo'),
       (13, 'A318', 'Airbus', 132, 'Inactivo'),
       (14, 'B747-400', 'Boeing', 416, 'Operativo'),
       (15, 'E175', 'Embraer', 88, 'Operativo'),
       (16, 'A380', 'Airbus', 500, 'Operativo'),
       (17, 'B737 MAX 8', 'Boeing', 178, 'Operativo'),
       (18, 'A340-300', 'Airbus', 295, 'Mantenimiento'),
       (19, 'B757-200', 'Boeing', 239, 'Operativo'),
       (20, 'A321', 'Airbus', 200, 'Operativo');


INSERT INTO pasajero (nombre, apellidos, documento, email)
VALUES ('Juan', 'Pérez', 'D12345678', 'juan.perez@example.com'),
       ('María', 'Gómez', 'D23456789', 'maria.gomez@example.com'),
       ('Carlos', 'Ramírez', 'D34567890', 'carlos.ramirez@example.com'),
       ('Ana', 'López', 'D45678901', 'ana.lopez@example.com'),
       ('Luis', 'Fernández', 'D56789012', 'luis.fernandez@example.com'),
       ('Laura', 'Sánchez', 'D67890123', 'laura.sanchez@example.com'),
       ('Jorge', 'Torres', 'D78901234', 'jorge.torres@example.com'),
       ('Lucía', 'Ruiz', 'D89012345', 'lucia.ruiz@example.com'),
       ('Pedro', 'Vargas', 'D90123456', 'pedro.vargas@example.com'),
       ('Sofía', 'Castillo', 'D01234567', 'sofia.castillo@example.com'),
       ('Miguel', 'Flores', 'D11223344', 'miguel.flores@example.com'),
       ('Isabel', 'Morales', 'D22334455', 'isabel.morales@example.com'),
       ('Fernando', 'Rojas', 'D33445566', 'fernando.rojas@example.com'),
       ('Valeria', 'Medina', 'D44556677', 'valeria.medina@example.com'),
       ('Diego', 'Gutiérrez', 'D55667788', 'diego.gutierrez@example.com'),
       ('Camila', 'Ortega', 'D66778899', 'camila.ortega@example.com'),
       ('Andrés', 'Navarro', 'D77889900', 'andres.navarro@example.com'),
       ('Paula', 'Cruz', 'D88990011', 'paula.cruz@example.com'),
       ('Ricardo', 'Méndez', 'D99001122', 'ricardo.mendez@example.com'),
       ('Elena', 'Herrera', 'D10111213', 'elena.herrera@example.com');
